//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: Schema.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Protobuf_UserRegistrationServiceClient, then call methods of this protocol to make API calls.
public protocol Protobuf_UserRegistrationService {
  func validate(_ request: Protobuf_ValidationRequest, callOptions: CallOptions?) -> UnaryCall<Protobuf_ValidationRequest, Protobuf_ValidationResponse>
  func register(_ request: Protobuf_UserCredential, callOptions: CallOptions?) -> UnaryCall<Protobuf_UserCredential, Protobuf_Empty>
}

public final class Protobuf_UserRegistrationServiceClient: GRPCClient, Protobuf_UserRegistrationService {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  /// Creates a client for the protobuf.UserRegistration service.
  ///
  /// - Parameters:
  ///   - connection: `ClientConnection` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous unary call to Validate.
  ///
  /// - Parameters:
  ///   - request: Request to send to Validate.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func validate(_ request: Protobuf_ValidationRequest, callOptions: CallOptions? = nil) -> UnaryCall<Protobuf_ValidationRequest, Protobuf_ValidationResponse> {
    return self.makeUnaryCall(path: "/protobuf.UserRegistration/Validate",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous unary call to Register.
  ///
  /// - Parameters:
  ///   - request: Request to send to Register.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func register(_ request: Protobuf_UserCredential, callOptions: CallOptions? = nil) -> UnaryCall<Protobuf_UserCredential, Protobuf_Empty> {
    return self.makeUnaryCall(path: "/protobuf.UserRegistration/Register",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// Usage: instantiate Protobuf_AuthenticationServiceClient, then call methods of this protocol to make API calls.
public protocol Protobuf_AuthenticationService {
  func authenticate(_ request: Protobuf_UserCredential, callOptions: CallOptions?) -> UnaryCall<Protobuf_UserCredential, Protobuf_AuthenticationResponse>
}

public final class Protobuf_AuthenticationServiceClient: GRPCClient, Protobuf_AuthenticationService {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  /// Creates a client for the protobuf.Authentication service.
  ///
  /// - Parameters:
  ///   - connection: `ClientConnection` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous unary call to Authenticate.
  ///
  /// - Parameters:
  ///   - request: Request to send to Authenticate.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func authenticate(_ request: Protobuf_UserCredential, callOptions: CallOptions? = nil) -> UnaryCall<Protobuf_UserCredential, Protobuf_AuthenticationResponse> {
    return self.makeUnaryCall(path: "/protobuf.Authentication/Authenticate",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol Protobuf_UserRegistrationProvider: CallHandlerProvider {
  func validate(request: Protobuf_ValidationRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Protobuf_ValidationResponse>
  func register(request: Protobuf_UserCredential, context: StatusOnlyCallContext) -> EventLoopFuture<Protobuf_Empty>
}

extension Protobuf_UserRegistrationProvider {
  public var serviceName: String { return "protobuf.UserRegistration" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Validate":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.validate(request: request, context: context)
        }
      }

    case "Register":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.register(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Protobuf_AuthenticationProvider: CallHandlerProvider {
  func authenticate(request: Protobuf_UserCredential, context: StatusOnlyCallContext) -> EventLoopFuture<Protobuf_AuthenticationResponse>
}

extension Protobuf_AuthenticationProvider {
  public var serviceName: String { return "protobuf.Authentication" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Authenticate":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.authenticate(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

